### PR TITLE
Update to toml_edit 0.22

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by sdroege** [comment]
Note that this time it does not involve a MSRV bump :)

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
Doesn't look CI supports your statement 👀

**Comment by sdroege** [comment]
Huh, did I fail reading and confused 7 with 9 :confused: Sorry!

**Comment by fornwall** [comment]
What is the status here? Bumping MSRV is unfortunately still a mess, with different opinions and conventions.

But perhaps the MSRV should just be bumped here without a major version bump - those caring about being compatible with rust 1.68 and 1.69 can still version pin (it's for sure not an ideal situation, but perhaps the most practical)?

**Comment by torokati44** [comment]
Just a note about MSRV: Rust 1.69 is now almost as old as 1.67 was when this PR was submitted. This may or may not mean anything, but I think it's relevant. :)

**Comment by torokati44** [comment]
_Bump...?_ :no_mouth:

**Comment by bkchr** [comment]
Done in: https://github.com/bkchr/proc-macro-crate/pull/52

**Pull request closed without merging**
