### PR TITLE
Bump `toml_edit` to `0.19`

### PR DESCRIPTION
**Pull request by MarijnS95**

### CODE REVIEW

**Comment by MarijnS95** [comment]
https://docs.rs/crate/toml_edit/0.19.3/source/Cargo.toml looks like this implies an MSRV bump to `1.60` otherwise `cargo` shows really obscure errors...: https://github.com/bkchr/proc-macro-crate/actions/runs/4241597018/jobs/7372022311

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
> https://docs.rs/crate/toml_edit/0.19.3/source/Cargo.toml looks like this implies an MSRV bump to `1.60` otherwise `cargo` shows really obscure errors...: https://github.com/bkchr/proc-macro-crate/actions/runs/4241597018/jobs/7372022311

Ahh nice ty! I was already wondering last time where this weird issue was coming from!

**Comment by MarijnS95** [comment]
I ran into it with `winit` and `objc` as well: instead of `cargo` clearly complaining about an MSRV mismatch it first tries to resolve **all** the crate dependencies which apparently use a mechanism that isn't supported by an older Rust version.

**Comment by MarijnS95** [comment]
@bkchr is anything else planned for a patch release or could we get this as a little version bump?

**Comment by bkchr** [comment]
Is that fixing an issue for you?

**Comment by MarijnS95** [comment]
Not much beyond the usual duplicate dependencies because many crates update at a desynced pace... But as there are many more such issues there turns out to be less of a hurry.

**Comment by bkchr** [comment]
I will try to release it later today!

**Comment by bkchr** [comment]
@MarijnS95 sorry for the delay! https://github.com/bkchr/proc-macro-crate/releases/tag/v1.3.1

**Pull request merged**
