### PR TITLE
Update to toml_edit 0.21

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by bkchr** [comment]
Does this release contains any important fixes?

**Comment by bkchr** [comment]
Or just to only compile the parsing features?

**Comment by sdroege** [comment]
Only that from what I can see, and updating this removes the duplicated `toml_edit` dependency in some of my crates :)

**Comment by bkchr** [comment]
Okay, I mainly asking because that would require another major version bump because of the MSRV change.

**Comment by bkchr** [comment]
Done. Ty any way for the pr!

**Pull request closed without merging**
